import type { LayoutConfig } from "@benos/core";

const ASSET_BASE = import.meta.env.BASE_URL;

export const layout: LayoutConfig = {
  dock: ["about-me", "launchpad", "ghostty", "math", "calligraphy", "biri"],
  desktop: [
    "about-me",
    "math",
    "kubernetes",
    "calligraphy",
    "linux",
    "ghostty",
    "docker",
    "bookshelf",
    "client",
    "lang",
    "stack",
    "hardware",
    "mc",
    "terraria",
    "philosophy",
    "history",
    "writing",
    "travel",
    "hackintosh",
    "python",
    "physics",
    "anime",
    "print3d",
    "milktea",
    "calc",
    "aifeng",
    "biri",
  ],
  allApps: [
    "about-me",
    "math",
    "kubernetes",
    "calligraphy",
    "linux",
    "ghostty",
    "docker",
    "bookshelf",
    // 客户端开发
    "android",
    "harmony",
    "mac",
    // 编程语言
    "java",
    "cpp",
    "kotlin",
    "golang",
    "rust",
    "haskell",
    "dart",
    "verilog",
    // 技术栈
    "deno",
    "bun",
    // 硬件
    "arduino",
    "esp32",
    "stm32",
    "raspberrypi",
    "micropython",
    "fpga",
    "xiaoxiongpi",
    "mc",
    "terraria",
    "philosophy",
    "history",
    "writing",
    "travel",
    "hackintosh",
    "python",
    "physics",
    "anime",
    "print3d",
    "milktea",
    "calc",
    "aifeng",
    "biri",
    // 系统工具，固定垫底
    "notes",
    "calculator",
    "clock",
    "calendar",
    "reminders",
    "sketch",
    "terminal",
    "settings",
  ],
  folders: [
    { id: "client", name: "客户端开发", apps: ["android", "harmony", "mac"] },
    {
      id: "lang",
      name: "编程语言",
      apps: ["java", "cpp", "kotlin", "golang", "rust", "haskell", "dart", "verilog"],
    },
    { id: "stack", name: "技术栈", apps: ["deno", "bun"] },
    {
      id: "hardware",
      name: "硬件开发",
      apps: [
        "arduino",
        "esp32",
        "stm32",
        "raspberrypi",
        "micropython",
        "fpga",
        "xiaoxiongpi",
      ],
    },
  ],
  workspaces: [
    {
      id: "1",
      name: "Work",
      wallpaper: `${ASSET_BASE}benos-wallpaper.jpg`,
      widgets: ["playground-clock", "playground-system"],
    },
    {
      id: "2",
      name: "Play",
      wallpaper: `${ASSET_BASE}macos-wallpaper-dark.jpg`,
      widgets: ["playground-system"],
    },
    {
      id: "3",
      name: "Focus",
      wallpaper: `${ASSET_BASE}ubuntu-wallpaper.png`,
    },
  ],
};
